version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.17
    - image: circleci/postgres:9.6-alpine
      environment: # environment variables for primary container
        POSTGRES_USER: postgres
    steps:
    - checkout
    - run:
        name: Update certificates
        command: sudo apt-get --allow-releaseinfo-change update && sudo apt upgrade -y
    - run:
        name: Get all dependencies
        command: |
          go mod download all
    - run:
        name: Test everything
        command: 
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega/...
          ginkgo -r -race -failFast -progress
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: build and push Docker images
        shell: /bin/bash
        command: |
          chmod +x ./build.sh
          ./build.sh





