FROM golang:1.11

RUN go get github.com/rotk2022/delinkcious/...

WORKDIR /go/src/github.com/rotk2022/delinkcious/svc/link_service
ADD ./main.go main.go
ADD ./service service

# Update
RUN apt-get --allow-releaseinfo-change update && apt upgrade -y

# Fetch dependencies
RUN go get -d -v


RUN CGO_ENABLED=0 GOOS=linux go build -o /link_service -a -tags netgo -ldflags '-s -w' .

EXPOSE 8080
ENTRYPOINT ["/link_service"]
